spring:
  datasource:
    url: jdbc:h2:mem:flow
    initialization-mode: always
    sql-script-encoding: UTF-8
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ROOT: INFO